name: futsallink_project
environment:
  sdk: ">=3.6.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.9.0
dev_dependencies:
  melos: ^6.3.2

flutter:
  assets:
    - assets/logo.svg