name: futsallink_ui
description: UI package for Futsallink platform containing shared UI components
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter

  # Core package dependency
  futsallink_core:
    path: ../futsallink_core

  # UI related packages
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  lottie: ^2.6.0
  shimmer: ^3.0.0
  flutter_staggered_animations: ^1.1.1

  # Form validation
  form_field_validator: ^1.1.0

  # Other utility packages
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  dartdoc: ^6.2.2

# Adicionando configuração da fonte
flutter:
  fonts:
    - family: Unbounded
      fonts:
        - asset: ../../assets/fonts/Unbounded-Regular.ttf
          weight: 400
        - asset: ../../assets/fonts/Unbounded-Light.ttf
          weight: 300
        - asset: ../../assets/fonts/Unbounded-ExtraLight.ttf
          weight: 200
        - asset: ../../assets/fonts/Unbounded-Medium.ttf
          weight: 500
        - asset: ../../assets/fonts/Unbounded-SemiBold.ttf
          weight: 600
        - asset: ../../assets/fonts/Unbounded-Bold.ttf
          weight: 700
        - asset: ../../assets/fonts/Unbounded-ExtraBold.ttf
          weight: 800
        - asset: ../../assets/fonts/Unbounded-Black.ttf
          weight: 900
  assets:
    - assets/images/logo.svg