name: futsallink_core
description: Core package for Futsallink platform containing shared domain logic
version: 0.1.0
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"
dependencies:
  flutter:
    sdk: flutter

  # Basic utilities
  equatable: ^2.0.7
  dartz: ^0.10.1
  uuid: ^3.0.5
  intl: ^0.19.0

  # State management 
  flutter_bloc: ^9.0.0

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6

  # Testing
  mocktail: ^1.0.0