name: futsallink_club
description: Futsallink app for futsal clubs and agents
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  google_fonts: ^4.0.4

  # Local packages
  futsallink_core:
    path: ../../packages/futsallink_core
  futsallink_ui:
    path: ../../packages/futsallink_ui
  futsallink_firebase:
    path: ../../packages/futsallink_firebase

  # State management
  flutter_bloc: ^9.0.0

  # Dependency injection
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.0

  # Media handling
  image_picker: ^1.0.4
  video_player: ^2.7.0
  chewie: ^1.7.0
  photo_view: ^0.14.0
  path_provider: ^2.1.1

  # UI enhancements
  smooth_page_indicator: ^1.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_local_notifications: ^18.0.1

  # Calendar and scheduling
  table_calendar: ^3.0.9
  syncfusion_flutter_calendar: ^28.1.37

  # Advanced search and filtering
  algolia: ^1.1.2

  # Others
  url_launcher: ^6.1.14
  permission_handler: ^10.4.3
  package_info_plus: ^4.1.0
  device_info_plus: ^9.0.3
  connectivity_plus: ^4.0.2
  flutter_flavor: ^3.1.1
  share_plus: ^7.1.0
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  injectable_generator: ^2.1.6
  hive_generator: ^2.0.1
  flutter_gen_runner: ^5.3.1
  mocktail: ^1.0.0
  bloc_test: ^10.0.0

# flutter:
#   uses-material-design: true
#   assets:
#     - assets/images/
#     - assets/icons/
#     - assets/animations/
  
# flutter_native_splash:
#   color: "#2E3B4E"
#   image: assets/images/splash_club.png
#   android: true
#   ios: true
  
# flutter_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icons/club_app_icon.png"
#   adaptive_icon_background: "#2E3B4E"
#   adaptive_icon_foreground: "assets/icons/club_app_icon_adaptive.png"

flutter_gen:
  output: lib/core/gen/
  integrations:
    flutter_svg: true